---
title: "Loader"
author: "Adeel Khan"
date: "01/05/2021"
output: html_document
---


```{css, echo=FALSE}
#preloader {
  position: fixed;
  left: 0;
  top: 0;
  z-index: 999;
  width: 100%;
  height: 100%;
  overflow: visible;
  background: rgba(255,255,255,0.5) url('C:/CEEW/Analysis/Purple_air/Scripts/Sensor_Alert/Images/Loader_2.gif') no-repeat center 20%;
}
```

<div id="preloader"></div>

```{js, echo=FALSE}
$(function(){ // this replaces document.ready
  $(window).on("load", function(){
    $('#preloader').fadeOut('slow', function() {
      $(this).remove();
    });
  });
});
```


```{r setup, include=FALSE}
## Loading Relevant packages
library(AirSensor);library(MazamaSpatialUtils)
library(lubridate);library(dplyr);library(Metrics);library(caret)
library(tidyverse);library(leaflet);library(DT);library(tidygeocoder);library(plotly)
```

## Summary {.tabset .tabset-fade .tabset-pills}

### Project Sensors
```{r,echo=F}
## Adding Spatial Data file
initializeMazamaSpatialUtils("C:/CEEW/Analysis/Purple_air/Spatial_data")
## Creating the pas object
pas <- pas_createNew(countryCodes = "IN",baseUrl = 'https://www.purpleair.com/json?all=true',
                     lookbackDays = 30,includePWFSL = FALSE)
## Geolocating from the latitude and longitude
Geolocation <- reverse_geo(
    lat = pas$latitude,
    long = pas$longitude,
    method = "osm",
    full_results = T
)
## Adding in the pas object
pas$City <- Geolocation$city
pas$District <- Geolocation$state_district
pas$State <- Geolocation$state
pas$lastSeen <- strftime(with_tz(pas$lastSeenDate,tz="Asia/Kolkata"),
                     format="%Y-%m-%d %H:%M")

## Selecting Project based Sensors
pas_subset <- pas %>% pas_filter(grepl('NASA',label)||grepl('UTN',label),!grepl("B",label))%>%select(label,lastSeen,City,District,State,pm25_1hr,pm25_1day,pm25_1week,temperature,humidity)
## Visualizing the table
DT::datatable(pas_subset)
```
